import Navbar from '../NavBar'
import Header from '../Header'
import Head from 'next/head'

export default function Layout({ children }) {
  return (
    <>
       <Head>
            <title>Features of ReactJs</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <div className="container px-4 md:px-0 max-w-6xl mx-auto -mt-32">
        <div className="mx-0 sm:mx-6">
            <Navbar/>
        </div>
      </div>
      <main>{children}</main>
      <footer >
         Footer
      </footer>
    </>
  )
}